#!/usr/bin/python

from cli import do_login
from lexer import parse, USAGE
from optparse import OptionParser
from sys import exit

if __name__ == '__main__':
    parser = OptionParser(usage = "usage: %prog <task description>")
    parser.add_option("-l", "--list", action="store_true", dest="show_tasks", default=False,
                      help="Show unfinished tasks")
    parser.add_option("-f", "--folders", action="store_true", dest="show_folders", default=False,
                      help="Show list of folders")
    parser.add_option("-g", "--goals", action="store_true", dest="show_goals", default=False,
                      help="Show list of goals")
    (options, args) = parser.parse_args()

    client = do_login()

    if options.show_tasks:
        tasks = [x.title for x in reversed(client.getTasks(comp=False))]
        for item in tasks: print "* " + item
        exit(0)
    elif options.show_folders:
        folders = [x.name for x in client.getFolders()]
        for item in folders: print "* " + item
        exit(0)
    elif options.show_goals:
        goals = [x.name for x in sorted(client.getGoals())]
        for item in goals: print "* " + item
        exit(0)
    elif len(args) >= 1:
        r = ' '.join(args)
    else:
        print USAGE
        import readline
        r = raw_input("Enter a task description: ")

    task = parse(r)
    client.addTask(**task)
    print
    print client.getTask(task['title'])
